### ISSUE TITLE
Usage with Excalidraw: Tools Panel Mouse Dragging: floats to right bottom screen

### ISSUE THREAD

**Issue by thomasdick-tortuetec** [nickmilo/LYT-Mode#27]
Dear Nick!

Thank you for your great contributions to Obsidian and it's usage!

Zsolt updated Excalidraw to Version 1.6.1. Since then, there is an issue when using the LYT-Mode 
When using Excalidraw and opening the Tools Pandel and click-moving it with the Mouse, the panel moves to the right, bottom direction of the screen.

To Reproduce
1. With Excalidraw Plugin and the LYT-Mode theme
2. Open a new Excalidraw Drawing and click on the Tools Panel
3. Try clicking on the 3 stripes on the panel top and moving the panal around
4. When moving the mouse, the panel will tend moving to the bottom right direction

Attached you find a Screencast showing the issue.

OS including version: Win11
Obsidian version: v0.13.23
Excalidraw version: 1.6.1

Best regards, Thomas

https://user-images.githubusercontent.com/58668945/156188657-1c0dc876-30a2-4454-b78b-924c8089aa9a.mp4

**Comment by zsviczian** [comment]
Seems this is causing the issue. If I comment this part out, the problem is gone...

```css
.excalidraw .Island {
    padding:    var(--scale-8-1)
                var(--scale-8-1)
                var(--scale-8-1)
                var(--scale-8-1);
    margin: var(--scale-2-4)
            var(--scale-2-4)
            var(--scale-2-4)
            var(--scale-2-4);
}

body .excalidraw .Island.App-menu__left {
    padding:    var(--scale-8-2)
                var(--scale-8-2)
                var(--scale-8-2)
                var(--scale-8-2);
}

.excalidraw .Island {
    padding:    var(--scale-8-1)
                var(--scale-8-1)
                var(--scale-8-1)
                var(--scale-8-1);
    margin: var(--scale-2-4)
            var(--scale-2-4)
            var(--scale-2-4)
            var(--scale-2-4);
}
```
